#!/bin/bash

. libtag

if ! isTagDir; then
	echo "This is not a tag directory."
	exit 1
fi

file="$(realtarget "$1")"
toRoot

if ! isValidTarget "$file"; then
	echo "This is not a valid target file."
	exit 2
fi

if isInFilelist "$file"; then
	echo "This file is already added"
	exit 2
fi

addToFilelist "$file"
moveFile "$file"
restore "$file"

echo "File '$file' successfully added."

exit 0

