#!/bin/bash

. libtag

tags=""
notTags=""
simulate=0

while getopts "sat:n:" arg; do
	case $arg in
		s)
			simulate=1
			;;
		a)
			;;
		t)
			tags="$tags $OPTARG"
			;;
		n)
			notTags="$notTags $OPTARG"
			;;
		*)
			echo "Unknown option."
			exit 1
	esac
done

if ! isTagDir; then
	echo "This is not a tag directory."
	exit 2
fi

if hasChanges > /dev/null; then
	echo "There are new files. Please add them before using a new filter."
	exit 2
fi

if test $simulate = 0; then
	clean
fi

getFilesForTags "$tags" "$notTags" | while read file; do
	if test $simulate = 1; then
		echo "$file"
	else
		restore "$file"
	fi
done


