#!/bin/bash

. libtag

file="$(realtarget "$1")"
toRoot

if ! isValidTarget "$file"; then
	echo "This is not a valid target file."
	exit 2
fi

if ! isInFilelist "$file"; then
	echo "The specified file is not added."
	exit 2
fi

deleteFromFilelist "$file"
deleteFile "$file"
rm "$file"
