#!/bin/bash

if test "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" = ""; then
	zenity --error --text="This only works on local files."
	exit 1
fi

if test ! -d ~/.tagbin; then
	zenity --error --text="Couldn't find tag installation."
	exit 1
fi

tmp="$(realpath ~/.tagbin)"
. "$tmp"/libtag
export PATH="$PATH:$tmp"

if ! isTagDir; then
	zenity --error --text="This is not a tag directory."
	exit 1
fi

globalTags="$(getTaglist)"

if test "$globalTags" = ""; then
	zenity --error --text="No tags known. Please add some before modifying them."
	exit 1
fi

for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
	tags="$(getTagsForFile "$file")"
	notTags="$(echo "$globalTags $tags" | tr ' ' '\n' | sort | uniq -u)"
	
	parameters="$(echo "$tags" | sed -e '/^$/d' | awk '{ print "TRUE " $1 }' | tr '\n' ' ') $(echo "$notTags" | sed -e '/^$/d' | awk '{ print "FALSE " $1 }' | tr '\n' ' ')"

	result=$(zenity --list --title="$file" --checklist --separator=" " --column="" --column="Tag" $parameters)
	if test $? != 0; then
		exit 1
	fi

	setTagsForFile "$file" "$result"
done
